### ISSUE TITLE
[master] Need help testing mouse input

### ISSUE THREAD

**Issue by zappybiby** [bethesirius/ChosunTruck#16]
Finally got mouse input to (kind of) work. Still needs revisions, but it is something we can work with for now. 

See my changes: https://github.com/ajchili/ChosunTruck/commit/dc021d4c4d6f032aaf27bf98c1a0c8cc49625694

Linux input for reference: https://github.com/bethesirius/ChosunTruck/blob/master/linux/src/main2.cc#L237

SendInput was incredibly difficult to implement so I'm avoiding that for now. SetCursorPos should do what we need it to do.

**Comment by zappybiby** [comment]
A couple questions:
1. Should we consider changing ld.setMinVote(55) to a higher value?
2. Does anyone know how to move the "imshow" window? ([I tried](https://github.com/ajchili/ChosunTruck/blob/dc021d4c4d6f032aaf27bf98c1a0c8cc49625694/ets2_auto_driving/main.cpp#L133))
3. Dividing the average [here](https://github.com/ajchili/ChosunTruck/blob/dc021d4c4d6f032aaf27bf98c1a0c8cc49625694/ets2_auto_driving/main.cpp#L186) gives wildly different results in terms of the truck compensating correctly. 13 works decently, but there is probably a better way to do this. 
4. I'm still not sure if [this](https://github.com/ajchili/ChosunTruck/blob/dc021d4c4d6f032aaf27bf98c1a0c8cc49625694/ets2_auto_driving/main.cpp#L193) centers the mouse correctly. Ideally it would move mouse to center, but its inconsistent.

**Comment by zappybiby** [comment]
Update: worked on it more https://github.com/ajchili/ChosunTruck/commit/99fa5178b96c58eda0b20161e7bcde782b23de9f

It's actually more broken then when I started this. That is pretty impressive.

I think I have the general idea of  what I need it to do now. I'm optimistic :)

**Comment by chi3236** [comment]
1. We can consider that, but any specific reasons to change the value?
2. I hope [this](http://docs.opencv.org/2.4/modules/highgui/doc/user_interface.html#movewindow) can be the solution

**Comment by chi3236** [comment]
2. [This](http://docs.opencv.org/2.4/modules/highgui/doc/user_interface.html#movewindow) can be the solution

**Comment by zappybiby** [comment]
Well I was testing a couple different things to try to see if I could make the program detect lines in different light conditions. Also when I posted that comment it was extremely dark and the program wasn't seeing any lines. I just turned on the lights of the truck to fix this.

setting setMinVote to 60 seemed to work better but I've changed it back down to 55 for now. I am still testing it.

I thought that changing the threshold values may help since it always seems to be a little darker than it should.

I tried AdaptiveThreshold to see if I can adapt to the brightness dynamically but this made it find too many lines instead. It was a fun experiment though!

Edit: was able to move windows, thank you! https://github.com/ajchili/ChosunTruck/commit/e980f95b875834b0ff7be6ea88ff7628e1441def

**Comment by zappybiby** [comment]
Made more progress: 
https://github.com/ajchili/ChosunTruck/commit/564b178c5ca36277fadd7b2a027119100e4bc761

See video here: https://www.youtube.com/watch?v=rqyvoFuGKKk&feature=youtu.be
(I crashed many times while doing this, now my engine stalls. lol)
I feel like the best way to get this to work would probably be dividing by an incremental amount.
For example, between 5 and -5 it divides by 10, between 5 to 10 and -5 to -10 it divides by 9...etc.

**Comment by chi3236** [comment]
Looks great! If the steering wheel recovers to the center quickly, it will move better.

**Comment by zappybiby** [comment]
Input is working a lot better now! https://github.com/ajchili/ChosunTruck/commit/fe4759d54436cbfa929de3e511a1610b8f4ed904

I don't have the time right now to manually fine-tune parameters of the PID controller, but it's working great so far.

See new video here: https://www.youtube.com/watch?v=iL2F__ENx5s&feature=youtu.be

The truck crashed at the end, but I think this is easily fixable.

**Comment by zappybiby** [comment]
New PID implementation https://github.com/ajchili/ChosunTruck/commit/eb601b4a4be88f2448d4c60decf951c53deafa5c

I will need to add Integral term in order to automatically determine the other terms (proportional + derivative)

**Comment by zappybiby** [comment]
Video of the new PID: https://www.youtube.com/watch?v=DYe3aTquavc&feature=youtu.be

Should be almost perfect with adaptive IPM.
