### ISSUE TITLE
Error open No such file run the ./ChosunTruck 

### ISSUE THREAD

**Issue by gotope** [bethesirius/ChosunTruck#17]
Hello,
The compile is OK, but blocked when execute the file.

 debian:~/ChosunTruck-master/linux$ ls
 build  ChosunTruck  Makefile  src  tensorbox
 
debian:~/ChosunTruck-master/linux$ ./ChosunTruck 
 error: open: No such file or directory

**Comment by bethesirius** [comment]
To get more your system information, type
`uname -a` 
and `cat /etc/debian_version` 
and `cat /usr/src/linux-headers-$(uname -r)/.config | grep UINPUT` 
in your terminal and send me the results.
Also, check whether `/dev/uinput` or `/dev/input/uinput` is existing.

**Comment by gotope** [comment]
@bethesirius 

 debian:~/Downloads$ uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

 debian:~/Downloads$ cat /etc/debian_version
8.7

 debian:~/Downloads$ cat /usr/src/linux-headers-$(uname -r)/.config | grep UINPUT
CONFIG_INPUT_UINPUT=m

 debian:~/Downloads$ ls /dev/uinput 
/dev/uinput

 debian:~/Downloads$ ls /dev/input/uinput
ls: cannot access /dev/input/uinput: No such file or directory

**Comment by bethesirius** [comment]
You have to enable uinput. Because I don't have debian system, i am not sure of this.
~Change the option `CONFIG_INPUT_UINPUT=m` to `CONFIG_INPUT_UINPUT=y` in the .config file.~

**Comment by gotope** [comment]
modify that to "y" and reboot, still failed, 
or need recompile the kernel with the headers?

 debian:~/ChosunTruck-master/linux$ cat /usr/src/linux-headers-$(uname -r)/.config | grep UINPUT
#CONFIG_INPUT_UINPUT=m
CONFIG_INPUT_UINPUT=y

 debian:~/ChosunTruck-master/linux$ ./ChosunTruck -D
error: open: No such file or directory

**Comment by bethesirius** [comment]
I'm sorry. Revert your .config file.
Uinput is built as a module in your debian. So, you need to insert the uinput module.
`modprobe uinput`
`lsmod|grep input`
`ls -l /dev/uinput`
I found this solution from https://bbs.archlinux.org/viewtopic.php?id=203169

**Comment by gotope** [comment]
@bethesirius  thanks, that's works.

// use sudo can create it now 
debian:~/ChosunTruck-master/linux$ sudo ./ChosunTruck      
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /usr/opencv-3.2.0/modules/core/src/matrix.cpp, line 522
terminate called after throwing an instance of 'cv::Exception'
  what():  /usr/opencv-3.2.0/modules/core/src/matrix.cpp:522: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat

**Comment by bethesirius** [comment]
Okay, I will change the ambiguous error message :)
And, your new OpenCV Error is difference from the uinput issue. I recommend that you close this and open new issue.

**Comment by mrasyidaqmar** [comment]
Hi, actually I had the same issue and ended up the same as the @gotope 's last posting, which is the OpenCV Error. Has this issue been opened or resolved somewhere? Thanks.

**Comment by chi3236** [comment]
@mrasyid No, it didn't. Please open a new issue with your enviornment like OS version, if you still have that trouble. Thanks.
