### ISSUE TITLE
Assertion error occurs ONLY at the first run after build

### ISSUE THREAD

**Issue by chi3236** [bethesirius/ChosunTruck#18]
[I changed IPM area code at windows/src/main.cpp](https://github.com/bethesirius/ChosunTruck/commit/ad87d2129df6b2b429a472d9927ab63bc7d25600)
This area setting works well in Linux without an assertion error, but in Windows, assertion error occurs.
```
OpenCV Error: Assertion failed (ssize.area() > 0) in cv::remapBilinear, file ...\opencv\sources\modules\imgproc\src\imgwarp.cpp, line 3868 
```
The error looks like this. It only occurs at the first execution after the build, and it does not occur after the second execution. The error can be ignored. Although the error occurs with the program stopped window, program runs well after a few seconds. Any ideas to deal with it?

**Comment by zappybiby** [comment]
[Try switching to Multi-threaded runtime libs (/MT)](https://i.imgur.com/oIssgHM.png)

I just updated my code to match that change and it works fine.

**Comment by gotope** [comment]
I set to Release version and run successful.

**Comment by chi3236** [comment]
@zappybiby Thanks!
